### ISSUE TITLE
ARC-Authentication-Results header missing spaces between fields

### ISSUE THREAD

**Issue by mdomsch** [trusteddomainproject/OpenARC#47]
Note below in the ARC-Authentication-Results header, spaces missing after header.from=value before spf=  and space missing after smtp.mailfrom value before dkim=.

Mail originates from mdomsch@nwayba.org (hosted in Google Apps for Nonprofits), coming to matt@domsch.com (my personal domain running sendmail).

```
Received: from mail-qt0-x235.google.com (mail-qt0-x235.google.com [IPv6:2607:f8b0:400d:c0d::235]) by do2.domsch.com (8.14.4/8.14.4) with ESMTP id v6JDcq7T011858 (version=TLSv1/SSLv3 cipher=AES128-GCM-SHA256 bits=128 verify=OK) for <matt@domsch.com>; Wed, 19 Jul 2017 13:38:53 GMT
Authentication-Results: do2.domsch.com; arc=none header.d=domsch.com
ARC-Seal: i=1; a=rsa-sha256; d=domsch.com; s=seal-20170618; t=1500471539; cv=none; b=vWlxJw7o/Bc9c3Zo6r1eNWPbJngpyUFs4pk6RjG+JfUtyTli2jfMPJtSNA8h+hXJc2buOONNso8wRZ859t65fsbQyI6igl+jLNsh87DN9FJTG9DSW/t22e3sYcq5QlLt526303uvypD84ZL8uMPx+tUGkBxxIp7/PJTWZv1w4cI=
ARC-Message-Signature: i=1; a=rsa-sha256; d=domsch.com; s=seal-20170618; t=1500471539; c=relaxed/simple; bh=J3cdEvkky4iIA0yvUAxMVQizQ+ffGENXna7N5SXIiq8=; h=DMARC-Filter:Authentication-Results:Authentication-Results:
	 Authentication-Results:Received:DKIM-Signature:
	 X-Google-DKIM-Signature:X-Gm-Message-State:X-Received:MIME-Version:
	 Received:From:Date:Message-ID:Subject:To:Content-Type; b=aEfPGZOtpLdqJOFJVp4//wdYRoZUWEUFOJjl5qv5FIxs1i1eaImT0VBpqjtzVGrQR59sojLHz40UVm5hxEmd4tjSc57MeZUSfhsAwINv03TGAHlOCQqCnwAX7SRD8HooH8S4I2wFzMUCV5xBMPaFNTWKQJK/Pr6KYwc+VqH8ht0=
ARC-Authentication-Results: i=1; do2.domsch.com; dmarc=pass (p=none dis=none) header.from=nwayba.orgspf=pass smtp.mailfrom=mdomsch@nwayba.orgdkim=pass (2048-bit key) header.d=nwayba.org header.i=@nwayba.org header.b=LjFv1MKs
DMARC-Filter: OpenDMARC Filter v1.3.2 do2.domsch.com v6JDcq7T011858
Authentication-Results: do2.domsch.com; dmarc=pass (p=none dis=none) header.from=nwayba.org
Authentication-Results: do2.domsch.com; spf=pass smtp.mailfrom=mdomsch@nwayba.org

```

**Comment by mdomsch** [comment]
I've seen this for a few days, most recently with HEAD 
commit c7000cbcc6edf497948b23c6b94b693e8da65c48
Author: Murray S. Kucherawy <msk@trusteddomain.org>
Date:   Wed Jul 19 02:08:06 2017 -0700

    Fix previous

**Comment by juh** [comment]
This was apparently fixed by commit [#767b85](https://github.com/mskucherawy/OpenARC/commit/767b85a9ed0f4beaf6837c11c195d4d81ece7486).

**Comment by andatche** [comment]
I'm still seeing this on HEAD (1bb9999b).

**Comment by xpunkt** [comment]
ARC-Authentication-Results: i=1; linode.junc.eu; dmarc=pass (p=quarantine dis=none) header.from=tapatalk.comdkim=pass (1024-bit key) header.d=tapatalk.com header.i=@tapatalk.com header.b=vQjEYNTH; dkim-atps=neutralspf=pass (client-ip=52.232.186.53; helo=email-gateway.yuku.com; envelope-from=trending@tapatalk.com; receiver=me@junc.eu) smtp.mailfrom=tapatalk.com; arc=none

head still have this bug

**Comment by AntiFreeze** [comment]
I had been seeing, but can no longer reproduce this issue using the latest code in develop.
